spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookmark?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
