server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookmark?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active:
    - dev
